# Pretty much a copy of Simon Willison's own build file
# @link https://github.com/simonw/simonw/blob/master/.github/workflows/build.yml

name: Build README

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '33 * * * *' # rebuilt once an hour at xx:33

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Update README
      run: |-
        python build_readme.py
        cat README.md
    - name: Commit and push if README changed
      run: |-
        git diff
        git config --global user.email "readme-bot@dunsap.com"
        git config --global user.name "README-bot"
        git diff --quiet || (git add README.md && git commit -m "Automated README update")
        git push
